# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'

target 'dashQ' do

pod 'AFNetworking'
pod 'SDWebImage'
pod 'JSONModel'
pod 'MagicalRecord'
pod 'UIActivityIndicator-for-SDWebImage'

end



